FROM python:3.12-slim

WORKDIR /app

# Copy the requirements first for better caching
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5002

ENV FLASK_APP=app.py
ENV FLASK_ENV=production

CMD ["python","app.py"]